apiVersion: v1
kind: Service
metadata:
  name: k8s-remote-runtime-server
  labels:
    app: k8s-remote-runtime-server
spec:
  selector:
    app: k8s-remote-runtime-server
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345
  type: LoadBalancer