apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: ghcr.io/smartmanoj/kevin-app:kevin
        command: ["uvicorn", "openhands.server.listen:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
        env:
        - name: LOG_ALL_EVENTS
          value: "true"
        - name: SANDBOX_RUNTIME_CONTAINER_IMAGE
          value: "ghcr.io/smartmanoj/kevin-sandbox:kevin-nikolaik"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: HOST_DOCKER_INTERNAL
          value: "host-gateway"
        envFrom:
        - secretRef:
            name: app-secrets
