apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      containers:
      - name: sandbox
        image: ghcr.io/smartmanoj/kevin-sandbox:kevin-ubuntu
        command: ["/openhands/micromamba/bin/micromamba", "run", "-n", "openhands", "poetry", "run", "python", "-u", "-m", "openhands.runtime.action_execution_server", "63710", "--working-dir", "/workspace", "--plugins", "agent_skills", "jupyter", "vscode", "vscode", "--username", "openhands", "--user-id", "1000"]
        ports:
        - containerPort: 63710
        - containerPort: 63711
        env:
        - name: VSCODE_PORT
          value: "63711"
        - name: VSCODE_CONNECTION_TOKEN
          value: "d5d0d35b-6693-4dbf-bc08-1a9f82bef097"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: port
          value: "63710"
