apiVersion: v1
kind: Service
metadata:
  name: kevin-sandbox-service
spec:
  selector:
    app: kevin-sandbox
  ports:
    - protocol: TCP
      port: 63710
      targetPort: 63710
      name: action-execution-server
    - protocol: TCP
      port: 63711
      targetPort: 63711
      name: vscode
  type: LoadBalancer